version: '3.8'

services:
  # PostgreSQL Database
  samap-db:
    image: postgres:14-alpine
    container_name: samap-database
    restart: unless-stopped
    environment:
      POSTGRES_DB: samap_db
      POSTGRES_USER: samap_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-samap_secure_password_2024}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - samap-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U samap_user -d samap_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Spring Boot Backend
  samap-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: samap-backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://samap-db:5432/samap_db
      SPRING_DATASOURCE_USERNAME: samap_user
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-samap_secure_password_2024}
      JWT_SECRET: ${JWT_SECRET:-samap_jwt_secret_key_2024_very_long_and_secure}
      JWT_EXPIRATION: 86400000
      JWT_REFRESH_EXPIRATION: 604800000
      LOGGING_LEVEL_COM_SAMAP: INFO
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics
    ports:
      - "8080:8080"
    depends_on:
      samap-db:
        condition: service_healthy
    networks:
      - samap-network
    volumes:
      - app_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/public/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  # Angular Frontend
  samap-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: samap-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      samap-backend:
        condition: service_healthy
    networks:
      - samap-network
    volumes:
      - nginx_logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis for Caching
  samap-redis:
    image: redis:7-alpine
    container_name: samap-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-samap_redis_password_2024}
    ports:
      - "6379:6379"
    networks:
      - samap-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RabbitMQ for Message Queue (Optional)
  samap-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: samap-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-admin123}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-/}
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    networks:
      - samap-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Prometheus for Metrics Collection
  samap-prometheus:
    image: prom/prometheus:latest
    container_name: samap-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - samap-network
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

  # Grafana for Monitoring Dashboard
  samap-grafana:
    image: grafana/grafana:latest
    container_name: samap-grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin123}
    ports:
      - "3000:3000"
    networks:
      - samap-network
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - samap-prometheus

networks:
  samap-network:
    driver: bridge
    name: samap-network

volumes:
  postgres_data:
    name: samap_postgres_data
  redis_data:
    name: samap_redis_data
  rabbitmq_data:
    name: samap_rabbitmq_data
  prometheus_data:
    name: samap_prometheus_data
  grafana_data:
    name: samap_grafana_data
  app_logs:
    name: samap_app_logs
  nginx_logs:
    name: samap_nginx_logs
