global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # SAMAP Application
  - job_name: 'samap-application'
    static_configs:
      - targets: ['samap-backend:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL Database
  - job_name: 'samap-postgres'
    static_configs:
      - targets: ['samap-db:5432']
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'samap-redis'
    static_configs:
      - targets: ['samap-redis:6379']
    scrape_interval: 30s

  # RabbitMQ Message Queue
  - job_name: 'samap-rabbitmq'
    static_configs:
      - targets: ['samap-rabbitmq:15672']
    scrape_interval: 30s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"
